### PR TITLE
Rename client/ to frontend/

### PR DESCRIPTION
**Pull request by codemonkey800**
## Description

This is something I've been wanting to do for a while to be consistent with the naming for the backend, but I wanted to wait until after the release since we were blasting out features the past few months.

This is a big change so it'd be great to merge this as soon as possible to reduce future merge conflicts.

## Demo

I deployed a stack to demonstrate that the deployment works even after the renaming.

https://dev-rename-client-to-frontend-frontend.dev.imaging.cziscience.com/

### CODE REVIEW

**Comment by justinelarsen** [comment]
I tried to access the link you posted to the test env, but I'm getting a 503 error 😬 
Screen Shot 2021-07-01 at 5 20 48 PM

**Comment by codemonkey800** [comment]
@justinelarsen Maybe try hard refreshing or accessing in incognito? It's working on my end 😢 

If it doesn't work then I'll do a bit more investigation

**Comment by justinelarsen** [comment]
@codemonkey800 Yes, that worked! Interesting.... 🤔

**Review by justinelarsen — APPROVED** [review]
LGTM! Minor change but touches a lot of files. Anything we should be worried about for prod deployment?

**Comment by codemonkey800** [comment]
@justinelarsen the test deployment should be enough verification that things will work correctly for prod deployments 😄

**Comment by codemonkey800** [comment]
@justinelarsen I'll monitor the staging deployment after merging. If anything prevents the website from working functionally, I'll do a revert of the PR

**Pull request merged**
