### PR TITLE
add favicon

### PR DESCRIPTION
**Pull request by kne42**
([relevant issue](https://airtable.com/tblNxANme1LbVQqq1/viwISga6FERUatih1/recNQovzA2CXBoPfH?blocks=hide))

### CODE REVIEW

**Comment by kne42** [comment]
@codemonkey800 not sure why but the tests keep failing

**Comment by codemonkey800** [comment]
@kne42 it was a super weird issue, but looks like you only had to re-run all jobs 🏃

**Review by liaprins-czi — APPROVED** [review]
Looks great to me!

**Review by justinelarsen — APPROVED** [review]
Looks good!

**Review by codemonkey800 — APPROVED** [review]
LGTM 🍨

**Pull request merged**
