### PR TITLE
rename `Mac` to `macOS`

### PR DESCRIPTION
**Pull request by 0x00b1**

### CODE REVIEW

**Review by codemonkey800 — APPROVED** [review]
amazing! 🎉

**Review by justinelarsen — APPROVED** [review]

**Comment by ziyangczi** [comment]
there is a test failing, not sure if related but probably need to be fixed if so

**Comment by codemonkey800** [comment]
Try running `yarn test:update`. I ran it on your branch and it gave me a different snapshot for some reason

**Comment by 0x00b1** [comment]
@codemonkey800 Odd. I ran `yarn test:update` to generate the snapshots. But after running it again, just now, it gave me new snapshots. Hopefully these work! 😎

**Comment by 0x00b1** [comment]
Hooray!

**Review by ziyangczi — APPROVED** [review]

**Pull request merged**
