### PR TITLE
Update footer design

### PR DESCRIPTION
**Pull request by codemonkey800**
https://footer-test-frontend.dev.imaging.cziscience.com/

https://user-images.githubusercontent.com/2176050/150903587-b6ffcedf-8d3f-4126-b4e8-19d5f2edf84e.mp4

### CODE REVIEW

**Review by liaprins-czi — CHANGES_REQUESTED** [review]
The breakpoint / overflow functionality looks perfect! The only thing I'd like to see updated is to have the napari logo and the new CZI logo be the same height. 

I think the napari logo needs to grow a little taller to be the same height as the separator line, I think this is the easiest. Or else shift it to be vertically centered with the line, and shrink the CZI logo to be the same height as napari logo (and also vertically centered with the line), but this might take more steps.

**Review by klai95 — APPROVED** [review]
Looks good to me!

**Comment by codemonkey800** [comment]
@liaprins-czi i've updated the icons, could take a look pls? 😄

**Review by liaprins-czi — APPROVED** [review]
Looks good to me! Thanks!

**Pull request merged**
