### PR TITLE
Copy button click feedback

### PR DESCRIPTION
**Pull request by codemonkey800**
## Description

Adds the missing click feedback when clicking on the copy button. This PR uses the [use-debounce](https://github.com/xnimorz/use-debounce) package to debounce the click feedback transition.

### Fixes
- https://airtable.com/shrw63y4RRus2DUB5/tblNxANme1LbVQqq1/viwISga6FERUatih1/recQRXhiAVjawcjYK

## Demo

https://napari-hub-bug-bash-frontend.dev.imaging.cziscience.com/

When the user clicks on the button, they'll immediately get feedback rendered in the UI. The checkmark and darker saturation will last for 2 seconds, but if the user clicks on the button before that, the timeout is restarted and they have to wait another 2 seconds.

https://user-images.githubusercontent.com/2176050/122491863-9f084f80-cf99-11eb-97c7-1ab039a2df72.mp4

### CODE REVIEW

**Review by liaprins-czi — APPROVED** [review]
Working for me! Also I tried it on Chrome's Inspector-simulated version of iPad (from my laptop, though) and it worked. I think this bug was originally reported from Kira saying if wasn't working on iPad

**Review by justinelarsen — APPROVED** [review]
This looks cool!

**Review by kne42 — CHANGES_REQUESTED** [review]
in the [link you provided](https://napari-hub-bug-bash-frontend.dev.imaging.cziscience.com/plugins/napari-btrack-reader) the padding looks off on iPad for all browsers, and on Chrome on desktop
IMG_0086

**Comment by liaprins-czi** [comment]
> in the [link you provided](https://napari-hub-bug-bash-frontend.dev.imaging.cziscience.com/plugins/napari-btrack-reader) the padding looks off on iPad for all browsers, and on Chrome on desktop
> IMG_0086

Yeah I saw that too (after I had already done my review for this issue) and I have made a bug bash issue for it (not sure if it was there in the original bug bash but I didn't notice it until this new link, too)

**Comment by codemonkey800** [comment]
> in the [link you provided](https://napari-hub-bug-bash-frontend.dev.imaging.cziscience.com/plugins/napari-btrack-reader) the padding looks off on iPad for all browsers, and on Chrome on desktop
> IMG_0086

Thanks for catching that, I'm not sure why I added a fix width to the button, but removing it should fix it. If there are still padding issues on iPad, it would be awesome if you could fix that in another PR since I don't have one 😢

**Comment by kne42** [comment]
fixed it for me 👍

**Pull request merged**
