### PR TITLE
Collection page UI

### LINKED ISSUE #511: P0 - /collections/[collection] page

### PR DESCRIPTION
**Pull request by codemonkey800**
Closes #511

# Demo

**The demo uses mock data**

https://napari-hub-collection-page.vercel.app/collections/point-detection-plugins

image

image

### CODE REVIEW

**Review by liaprins-czi — CHANGES_REQUESTED** [review]
This is looking nice! There are just a few things to update to match the designs more closely:
- The description length per plugin (provided by the curator of the collection) is exceeding the maximum character count (I can't remember the exact number of characters we settled on, but [in this file it says ~100 characters](https://docs.google.com/document/d/1NgYCld9kMxwXa15BL-wzE--MqdMuZ0D2QWQ-NnCDKVc/edit#heading=h.p3hcfeo9obcq); @neuromusic or @dannielle can you remember?
- There should be 75px between bottom of last plugin and top of footer (this is for all pages, not just the individual collection page)
- Line height on the curator's byline (describing their name + title + institution) should be 1.5 (21px when type size is `14px, but right now it is ~16.5px)
- Plugin card layout doesn't match plugin card layout design on the home page in a few ways, including:
- Plugin author name is too large (and doesn't scale down at mobile narrower sizes)
- Not enough spacing between plugin name and PyPI package name
- Not enough spacing between PyPI package name and plugin description (provided by plugin dev)
- Not enough spacing between description (provided by plugin dev) and plugin dev name

Let me know if you have any questions or concerns. Thanks!

**Review by liaprins-czi — APPROVED** [review]
I think it all looks good to me now @codemonkey800 ! Sorry about the lack of specificity for the spacing, I'd thought it'd be easier to re-use the code for the plugin cards from the homepage, but it looks good to me now.

**Comment by codemonkey800** [comment]
@liaprins-czi  sounds good, it might be a line spacing thing because the plugin display name and pypi name didn't have the correct line spacing until I pushed my fixes. thank you!! 🔥

**Comment by liaprins-czi** [comment]
@codemonkey800 Oh, yeah that makes sense about the line spacing... It think this will also be much easier when we have our own SDS library sorted out!

**Pull request merged**
