### PR TITLE
Show warning for mismatched repo URLs

### PR DESCRIPTION
**Pull request by codemonkey800**
## Description

Updates the preview sticky header to render a warning if the wheel's code repository doesn't match the action repository.

### With matching repos

https://napari-hub-preview-matching-repos.vercel.app

image

### With mismatched repos

https://napari-hub-preview-mismatch-repo.vercel.app

image

### CODE REVIEW

**Comment by codemonkey800** [comment]
Added @neuromusic @liaprins-czi @DragaDoncila for review of the label and either @kne42, @klai95 or @justinelarsen for code review 😄

**Review by liaprins-czi — DISMISSED** [review]
Thanks for making this update! I just have a few suggested changes for the readability of the message:

- [ ] the second phrase of the first sentence in italics to indicate it needs to be paid attention to
- [ ] and then have “Learn more.” not in parenthesis and its own sentence (with the period at the end included as part of the link
- [ ] a period after last sentence
- [ ] add "the" before "napari hub" in last sentence

So it’d look like:

This preview of napari-demo was generated from [chanzuckerberg/napari-demo#5](url), _but your metadata points to [potating-potato/napari-demo](url) as the source code._ [Learn more.](url)
It is not live on the napari hub.

Thanks!

**Comment by codemonkey800** [comment]
Thanks for the feedback @liaprins-czi I've updated the text to match the styling now:

https://napari-hub-preview-mismatch-repo.vercel.app

image

**Review by liaprins-czi — COMMENTED** [review]
Thanks Jeremy! One last itsy bitsy thing: can we add a period after "It is not live on the napari hub" for grammatical consistency? Thanks so much!

**Comment by codemonkey800** [comment]
oops, didn't realize it was missing. added!

**Review by DragaDoncila — APPROVED** [review]
LGTM!

**Comment by DragaDoncila** [comment]
@codemonkey800 here is the link to the relevant section in the doc, now that it's been merged: https://github.com/chanzuckerberg/napari-hub/blob/main/docs/setting-up-preview.md#seeing-a-warning-message

**Comment by codemonkey800** [comment]
> @codemonkey800 here is the link to the relevant section in the doc, now that it's been merged: https://github.com/chanzuckerberg/napari-hub/blob/main/docs/setting-up-preview.md#seeing-a-warning-message

Awesome, thank you @DragaDoncila!!

**Review by neuromusic — APPROVED** [review]
fantastic!

**Pull request merged**
