### PR TITLE
GitHub flavored Markdown

### PR DESCRIPTION
**Pull request by 0x00b1**

### CODE REVIEW

**Review by codemonkey800 — COMMENTED** [review]
`renderDescription()` is only used for converting the markdown to plain text so that the search engine doesn't index on markdown syntax.

The component responsible for actually rendering Markdown is `Markdown.tsx`, and it already has this plugin:

https://github.com/chanzuckerberg/napari-hub/blob/75e867e90878e48cec4b2d0382cb8c9acfa76e17/client/src/components/common/Markdown/Markdown.tsx#L23-L29

**Comment by 0x00b1** [comment]
Thank you @codemonkey800!

**Comment by 0x00b1** [comment]
@codemonkey800 Can I close this since we likely don't need it for search?

**Comment by codemonkey800** [comment]
> @codemonkey800 Can I close this since we likely don't need it for search?

sounds good, I had a similar hunch but wanted to see if you could find a use case 😄

**Pull request closed without merging**
