### PR TITLE
update value prop bullet

### PR DESCRIPTION
**Pull request by neuromusic**
new text: "Understand how to install into napari"

### CODE REVIEW

**Review by sofroniewn — APPROVED** [review]
Thanks for these changes, they look good to me!!

**Comment by LCObus** [comment]
Understand isn't the most active verb (and i'm splitting hairs but it implies the user will understand, which we can't guarantee)
Could I suggest a more active verb of "**learn how to install into napari**"?

**Comment by neuromusic** [comment]
thoughts on @LCObus's rec, @sofroniewn?

**Comment by sofroniewn** [comment]
> "learn how to install into napari"?

also fine with me

**Comment by sofroniewn** [comment]
> i'm splitting hairs but it implies the user will understand, which we can't guarantee

love the attention to detail 🚀

**Pull request merged**
