### PR TITLE
Removing deprecated endpoints

### PR DESCRIPTION
**Pull request by manasaV3**
## Description
Relates to https://github.com/chanzuckerberg/napari-hub/issues/1202

Changes introduced: 
- Removes `/plugins` and `/plugins/excluded` api and related components
- Updates bdd-test to remove tests for the deprecated endpoints
- Cleans up bdd-test to better follow pep8 guidelines for formatting and typing hints
- Removes read permission to the `plugin_blocked` table for the backend module
- Removes unused API key from backend lambda env variable and update cloudwatch event rule that is no longer needed. 

### Notes
- Do not merge this PR until the adoption of `/plugin/index/all` is confirmed by internal users.

### CODE REVIEW

**Review by aganders3 — DISMISSED** [review]
I'm still not set up to run the BDD tests locally, but LGTM!

**Comment by manasaV3** [comment]
> I'm still not set up to run the BDD tests 

Hopefully, the following helps. Please let me know if you run into any issues with this. 😸 

#### Setting up to run BDD tests

You might have to run `pip install` on `bdd-test-requirements.txt` to ensure you have all the dependencies needed for the BDD tests. 
```
pip install -r bdd-test-requirements.txt
```

#### Running BDD tests locally

If you want to run the tests against your local environment, ensure you have the backend application running locally in another terminal, and run the following command from the backend folder:
```
PORT=12345 python -m pytest bdd_tests
```
`12345` is the default port; you don't need to specify the PORT variable if you run your application on the default port. But you can use that if you run your Flask application on a different port. 

#### Running BDD tests against staging and prod

The prefix variable is helpful in cases where you are running against non-local environments. For staging and production, it can be run by setting the `PREFIX` value to `staging` and `prod`, respectively. For example, to run the BDD tests against the prod-environment, use the following command:
```
PREFIX=prod python -m pytest bdd_tests
```

#### Running BDD tests against dev environments

The `PREFIX` variable also comes to the rescue in this case. The dev environment can have any prefix, so you would have to specify the dev-branch name that acts as the prefix for the environment. For example, to run the BDD tests against the `dev-shared` dev-environment, use the following command:

```
PREFIX=dev-shared python -m pytest bdd_tests
```

**Review by richaagarwal — APPROVED** [review]
So much deleted code 😍

Looks good to me. I'm assuming we'll wait until @seankmartin has confirmed their team has migrated away from these endpoints before merging in?

Just to confirm, are we keeping `/plugins/<plugin>/versions/<version> `, `/manifest/<plugin>` and `/manifest/<plugin>/versions/<version>` around for internal testing/utility purposes?

**Comment by manasaV3** [comment]
>  I'm assuming we'll wait until @seankmartin has confirmed their team has migrated away from these endpoints before merging in?

Yes, that is correct.

> Just to confirm, are we keeping `/plugins/<plugin>/versions/<version> `, `/manifest/<plugin>` and `/manifest/<plugin>/versions/<version>` around for internal testing/utility purposes?

Yes, retained these two endpoints as they provide functionality that is not covered in the current public endpoints and could prove useful in internal testing/debugging.

**Comment by seankmartin** [comment]
Hey @manasaV3, we are using the endpoint [`plugin\index\all`](https://api.napari-hub.org/plugins/index/all) for our projects now, thanks!

**Comment by richaagarwal** [comment]
@manasaV3 Would you want to merge this before regression testing starts today?

**Pull request merged**
