### PR TITLE
Fix TOC highlighting

### LINKED ISSUE #157: right nav highlighting jumps to end
*from June 2020 pre-launch bug bash*

**Created by**: justin

## Description 

when I click the next-to-last item on the right nav, if the last two sections are short, the last item gets highlighted. this happens on the about page as well as plugin pages

## Info

**Bug source**: wide

**Browser**: chrome

**PR**: *none*

## Attachments

https://dl.airtable.com/.attachments/f1adb5121031e79c3bdb51bfc8e8d8b7/c9fe1aa4/image.png

### PR DESCRIPTION
**Pull request by codemonkey800**
## Description

Closes #157 

This PR fixes the active header highlighting for the `TableOfContents` component. This updates the logic so that it implements the [following missing behavior](https://github.com/chanzuckerberg/napari-hub/issues/157#issuecomment-897084157):

> when I click the second-to-last item in the nav:❗️it does not apply selected style to the clicked-nav item (instead keeps same style on last section's nav item). The treatment should change to show second-to-last section's nav item in selected treatment. (Also the page doens't scroll, but that's to be expected because the second-to-last section is also too short to touch the top... but if it's not too short then it should).

## Demos

https://fix-toc-frontend.dev.imaging.cziscience.com/plugins/napari-bioformats

### Highlight Selected

Clicking on a TOC will highlight the selected item, even if there's not enough space for it to be active on scroll, and it'll stay highlighted until the user scrolls again.

https://user-images.githubusercontent.com/2176050/129811889-09417b53-6935-408f-ab5d-4bd24abfde1e.mp4

### Highlight on Initial Load

When sharing a link to a heading directly, the page will:

1. Scroll to the heading
1. Highlight the corresponding TOC item

https://user-images.githubusercontent.com/2176050/129414445-370a01a1-80e4-484f-9241-0948e933c499.mp4

#### Chrome / Edge / Safari

The above browsers will maintain the previous scroll position on reload and highlight the next header in the viewport.

https://user-images.githubusercontent.com/2176050/129414436-c9c442d3-6dcc-40b1-8c5a-5be833ac3ce2.mp4

#### Firefox

Firefox is the only browser that scrolls back to the heading on reload (instead of maintaining the previous scroll position).

https://user-images.githubusercontent.com/2176050/129414418-9604bf6b-d3d9-47f7-ab23-dae3ff1172ab.mp4

### CODE REVIEW

**Review by kne42 — APPROVED** [review]
nice job, LGTM!

**Comment by neuromusic** [comment]
nice!! super clean & consisten

**Review by neuromusic — APPROVED** [review]
LGTM

**Review by klai95 — APPROVED** [review]
Nicely done! LGTM!

**Review by liaprins-czi — COMMENTED** [review]
Thanks for all your efforts on this issue! I actually think that originally (before this PR) it was working _almost_ as I expected it to, but not the changes in the PR are making it do unexpected things from my perspective.

In the first video it shows the highlightign applying to the last nav item when scroll to the bottom, but I would not expect that to ever happen (unless user clicked that nav item). In the following videos, it shows the highlight applying to nav items that after scrolling away from them and then back down, but they are too low down for the highlighting to make sense when scrolling (only when initially clicked). 

Then again, everyone else is not seeming confused by this LOL, and maybe it is too tricky to get the UX I am describing to be worth the time and effort; if so no worries! And let me know if you want to hop on a call to discuss if this is not clear!

**Comment by codemonkey800** [comment]
After discussing with @liaprins-czi , the incorrect behavior was that the TOC was jumping to the last section when scrolling to the bottom.

I've removed the logic for jumping to the last section and updated the `Highlight Selected` demo:

https://user-images.githubusercontent.com/2176050/129811889-09417b53-6935-408f-ab5d-4bd24abfde1e.mp4

**Review by liaprins-czi — APPROVED** [review]
💙  it! This looks / functions perfectly to me! Thanks for all your efforts!

**Pull request merged**
