### PR TITLE
Improve support for large number of categories

### LINKED ISSUE #421: Improve support for plugins with large numbers of categories
As @haesleinhuepf noted, our current design is not well suited to plugins with large numbers of categories.

### Discussed in https://github.com/chanzuckerberg/napari-hub/discussions/374

<div type='discussions-op-text'>

<sup>Originally posted by **haesleinhuepf** December 24, 2021</sup>
Hi all, 

just a suggestion about where the EDAM ontology entries are shown. At the moment, the user has to scroll down quite a bit until the actual documentation / readme of a plugin appears. I suggest to display all the useful metadata of plugins in other places (left/right), and not on top of the page. It's not urgent to work on this btw.

Happy Holidays!
Robert

image
</div>

### PR DESCRIPTION
**Pull request by codemonkey800**
Fixes #421 

This implements the following functionality:

1. Highlight categories for active filters on search and plugin pages
2. Sorts active categories to the front of the category list
3. [Allows sharing highlighted categories for plugin pages](https://cat-pill-frontend.dev.imaging.cziscience.com/plugins/cellfinder-napari?workflowStep=Image+annotation&workflowStep=Image+feature+detection&imageModality=Fluorescence+microscopy&imageModality=Multi-photon+microscopy)

Demo: https://cat-pill-frontend.dev.imaging.cziscience.com/

### CODE REVIEW

**Comment by codemonkey800** [comment]
@liaprins-czi one thing about this that doesn't follow the design is the pills and button change into a column layout when expanded. making it inline is a bit tricky to do, so is it okay if we don't do inline or maybe create a separate follow-up issue for it?

image

**Review by liaprins — APPROVED** [review]
This looks superb to me! 🤠 🦭

Edit: oops, somehow signed in under my personal GH acct... re-reviewing with my CZI GH acct now!

**Review by liaprins-czi — APPROVED** [review]
Looks god to me in this GitHub account, too! 🦜🦚

**Review by neuromusic — APPROVED** [review]
LGTM!!

**Pull request merged**
